### ISSUE TITLE
 App button support drag

### ISSUE THREAD

**Issue by molvqingtai** [molvqingtai/WebChat#31]
Some website features will be blocked by the APP button, such as the AI button on GitHub, so the position needs to be draggable.

![image](https://github.com/user-attachments/assets/46090e82-38ff-4ae1-9207-6991ecab6f34)

**Comment by GuanCun** [comment]
我也需要这个功能

**Comment by molvqingtai** [comment]
Already supported: 4eba638a367d4be2dc3d0b3e378298fd98a9ff5d

[v1.4.0](https://github.com/molvqingtai/WebChat/releases/tag/v1.4.0)
