### ISSUE TITLE
chorme插件安装完WebChat 根本没法使用

### ISSUE THREAD

**Issue by yxw007** [molvqingtai/WebChat#35]
# 现象
![演示效果](https://github.com/user-attachments/assets/c177b43d-d30c-4a7a-8625-6e18b67b3472)

顺便问一下，你视频录制用的什么软件？

**Comment by Megrax** [comment]
点击网页右下角的这个图标使用
![CleanShot 2024-10-11 at 10 54 49@2x](https://github.com/user-attachments/assets/90200423-5175-45ec-86a5-b03bf9456b31)

**Comment by yxw007** [comment]
@Megrax  哈哈，没有注意到这小东西，建议还是给个提示，不然大家还以为没法使用
