### ISSUE TITLE
希望增加除p2p以外的连接方式，例如自建中转服务器

### ISSUE THREAD

**Issue by Le1a** [molvqingtai/WebChat#37]
因为受网络因素影响，p2p的概率并不高。利用自建中转服务器可以让更多用户参与进来

**Comment by molvqingtai** [comment]
In the future, we will look for stable and open Signaling services instead of building our own.

**Comment by GuanCun** [comment]
是的，我也遇到了网络的问题，我几乎看不到朋友，我只能见到很少的陌生人

**Comment by ZAIDU-Miren** [comment]
> 将来，我们将寻求稳定、开放的信令服务，而不是自己构建。-----------谷歌翻译------------未来，我们将寻找稳定、开放的信令服务，而不是构建自己的信令服务。

希望这一天快点到来，上网冲浪，摸鱼，大家都会，如果在在自己的博客，引导大家安装这个插件，岂不是也实现了聊天室的功能，客服，反正还是很多可能发生

**Comment by molvqingtai** [comment]
@Le1a @GuanCun @ZAIDU-Miren 
The previous Notr network has now been replaced with a new peer service, which should be more stable. If you encounter any issues during use, please let us know.

version 1.3.0
